# -*- coding: utf-8 -*-
"""python-tutorial-11.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fp2icAN-WZWGcs9MWQhKGksAdGyzlqs1

##**Section 11. Modules & Packages -**

###Modules
"""

# main.py
import pricing


net_price = pricing.get_net_price(
    price=100,
    tax_rate=0.01
)

print(net_price)

from sales.order import create_sales_order

create_sales_order()

"""###Module Search Path"""

import module
import sys

for path in sys.path:
    print(path)

"""### __name__ variable"""

def calculate_tax(price, tax):
    return price * tax


def print_billing_doc():
    tax_rate = 0.1
    products = [{'name': 'Book',  'price': 30},
                {'name': 'Pen', 'price': 5}]

    # print billing header
    print(f'Name\tPrice\tTax')

    # print the billing item
    for product in products:
        tax = calculate_tax(product['price'], tax_rate)
        print(f"{product['name']}\t{product['price']}\t{tax}")


print(__name__)

"""###Packages"""

# main.py
from sales.order import create_sales_order as create_order
from sales.delivery import create_delivery as start_delivery
from sales.billing import create_billing as issue_billing


create_order()
start_delivery()
issue_billing()